#############################################################################
# Makefile for building: Easy-work
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Oct 16 22:45:20 2012
# Project:  Easy-work.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Easy-work.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-General \
		sub-Major_components

General//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) General/ || $(MKDIR) General/ 
	cd General/ && $(QMAKE) /home/keygen/Документы/Easy-work/General/General.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-General-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) General/ || $(MKDIR) General/ 
	cd General/ && $(QMAKE) /home/keygen/Документы/Easy-work/General/General.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-General: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE)
sub-General-make_default: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) 
sub-General-make_first: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) first
sub-General-all: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) all
sub-General-clean: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) clean
sub-General-distclean: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) distclean
sub-General-install_subtargets: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) install
sub-General-uninstall_subtargets: General//$(MAKEFILE) FORCE
	cd General/ && $(MAKE) -f $(MAKEFILE) uninstall
Major_components//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Major_components/ || $(MKDIR) Major_components/ 
	cd Major_components/ && $(QMAKE) /home/keygen/Документы/Easy-work/Major_components/Major_components.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Major_components-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Major_components/ || $(MKDIR) Major_components/ 
	cd Major_components/ && $(QMAKE) /home/keygen/Документы/Easy-work/Major_components/Major_components.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Major_components: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE)
sub-Major_components-make_default: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) 
sub-Major_components-make_first: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) first
sub-Major_components-all: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) all
sub-Major_components-clean: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) clean
sub-Major_components-distclean: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Major_components-install_subtargets: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) install
sub-Major_components-uninstall_subtargets: Major_components//$(MAKEFILE) FORCE
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: Easy-work.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Easy-work.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Easy-work.pro

qmake_all: sub-General-qmake_all sub-Major_components-qmake_all FORCE

make_default: sub-General-make_default sub-Major_components-make_default FORCE
make_first: sub-General-make_first sub-Major_components-make_first FORCE
all: sub-General-all sub-Major_components-all FORCE
clean: sub-General-clean sub-Major_components-clean FORCE
distclean: sub-General-distclean sub-Major_components-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-General-install_subtargets sub-Major_components-install_subtargets FORCE
uninstall_subtargets: sub-General-uninstall_subtargets sub-Major_components-uninstall_subtargets FORCE

sub-General-check: General/$(MAKEFILE)
	cd General/ && $(MAKE) -f $(MAKEFILE) check
sub-Major_components-check: Major_components/$(MAKEFILE)
	cd Major_components/ && $(MAKE) -f $(MAKEFILE) check
check: sub-General-check sub-Major_components-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

